### PR TITLE
Update React and other deps

### LINKED ISSUE #349: Version 1.9.0 can't be installed with React 18
When trying to install @auth0/auth0-react@1.9.0 in a React 18 project, npm fails with:
```shell
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.11.0 || ^17" from @auth0/auth0-react@1.9.0
npm ERR! node_modules/@auth0/auth0-react
```

### PR DESCRIPTION
**Pull request by adamjmcgrath**
### Description

- Update the dev deps (tests) and playground to use React@18
- Add React 18 to peer deps
- Update a bunch of other deps

### References

fixes #349 

### Testing

Login via the playground (which is running on React 18)

### Checklist

- [ ] I have added documentation for new/changed functionality in this PR or in auth0.com/docs
- [ ] All active GitHub checks for tests, formatting, and security are passing
- [ ] The correct base branch is being used, if not `master`

### CODE REVIEW

**Review by frederikprijck — APPROVED** [review]

**Comment by adamjmcgrath** [comment]
Need to fix this build too...

**Comment by cyyprezz** [comment]
Did u have a timeline when this issue is fixed? Or is there a workaround atm?

**Review by frederikprijck — APPROVED** [review]

**Comment by dkobierski** [comment]
@adamjmcgrath when can we expect to get this merged and released?

**Comment by benjivesterby** [comment]
@frederikprijck when will the new version which supports React 18 be released to `npm`?

**Comment by frederikprijck** [comment]
Yes, we will most likely cut a release today @benjivesterby .

**Comment by frederikprijck** [comment]
We cut a new release, you should be able to use React 18 with version 1.10.0.

**Pull request merged**
